import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';
const monigue = localFont({
    src: './fonts/MoniguedemoRegular-gwlL1.otf',
    variable: '--font-monigue',
});
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({ children, }) {
    return (<html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${monigue.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>);
}
